// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { EntriesCreateEntryData, EntriesCreateEntryErrors, EntriesCreateEntryResponses, EntriesDeleteEntryData, EntriesDeleteEntryErrors, EntriesDeleteEntryResponses, EntriesGetEntriesData, EntriesGetEntriesResponses, EntriesUpdateEntryData, EntriesUpdateEntryErrors, EntriesUpdateEntryResponses, RootRootData, RootRootResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 *
 * 画面表示を行います。
 */
export const rootRoot = <ThrowOnError extends boolean = false>(options?: Options<RootRootData, ThrowOnError>) => {
    return (options?.client ?? client).get<RootRootResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Get Entries
 *
 * 掲示板の全エントリーを取得します。
 */
export const entriesGetEntries = <ThrowOnError extends boolean = false>(options?: Options<EntriesGetEntriesData, ThrowOnError>) => {
    return (options?.client ?? client).get<EntriesGetEntriesResponses, unknown, ThrowOnError>({
        url: '/entries',
        ...options
    });
};

/**
 * Create Entry
 *
 * 掲示板にエントリーを新規追加します。
 */
export const entriesCreateEntry = <ThrowOnError extends boolean = false>(options: Options<EntriesCreateEntryData, ThrowOnError>) => {
    return (options.client ?? client).post<EntriesCreateEntryResponses, EntriesCreateEntryErrors, ThrowOnError>({
        url: '/entries',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Entry
 *
 * IDを指定して掲示板のエントリーを削除します。
 */
export const entriesDeleteEntry = <ThrowOnError extends boolean = false>(options: Options<EntriesDeleteEntryData, ThrowOnError>) => {
    return (options.client ?? client).delete<EntriesDeleteEntryResponses, EntriesDeleteEntryErrors, ThrowOnError>({
        url: '/entries/{entry_id}',
        ...options
    });
};

/**
 * Update Entry
 *
 * IDを指定して掲示板のエントリーを更新します。
 */
export const entriesUpdateEntry = <ThrowOnError extends boolean = false>(options: Options<EntriesUpdateEntryData, ThrowOnError>) => {
    return (options.client ?? client).patch<EntriesUpdateEntryResponses, EntriesUpdateEntryErrors, ThrowOnError>({
        url: '/entries/{entry_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
